site_name: GLVis
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

repo_url: https://github.com/glvis/glvis

pages:
- Home: index.md
- Features: features.md
- Documentation:
  - 'Building GLVis': building.md
  - 'Options and Use': options-and-use.md
  - 'Mesh Formats': mesh-formats.md
  - 'Parallel Visualization': parallel-visualization.md
  - 'Curvilinear VTK Meshes': curvilinear-vtk-meshes.md
  - 'NURBS Meshes': nurbs.md
  - 'About': about.md
- Gallery: gallery.md
- Download: download.md

theme_dir: template

include_next_prev: false  # turn of next/previous buttons

google_analytics: ['UA-101697-4', 'glvis.org']
